// <auto-generated />
namespace RSTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requistionenablenull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requistionenablenull));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201040564_requistion-enable-null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
